const users = [
  {
    id: 1,
    first_name: "Efren",
    email: "eolkowicz0@redcross.org",
    gender: "Male",
    mobile_no: "335 658 0857",
  },
  {
    id: 2,
    first_name: "Hadleigh",
    email: "hwatkiss1@about.com",
    gender: "Male",
    mobile_no: "869 525 2171",
  },
  {
    id: 3,
    first_name: "Kirsten",
    email: "kcopcutt2@deliciousdays.com",
    gender: "Female",
    mobile_no: "790 340 0506",
  },
  {
    id: 4,
    first_name: "Kent",
    email: "kprys3@tinypic.com",
    gender: "Male",
    mobile_no: "997 617 5711",
  },
  {
    id: 5,
    first_name: "Neville",
    email: "ndoog4@amazon.co.jp",
    gender: "Male",
    mobile_no: "205 365 7259",
  },
  {
    id: 6,
    first_name: "Sigismond",
    email: "selmore5@ibm.com",
    gender: "Male",
    mobile_no: "970 466 3653",
  },
  {
    id: 7,
    first_name: "Cicely",
    email: "coakland6@utexas.edu",
    gender: "Female",
    mobile_no: "512 399 1222",
  },
  {
    id: 8,
    first_name: "Rhys",
    email: "rcottis7@geocities.jp",
    gender: "Male",
    mobile_no: "132 652 8568",
  },
  {
    id: 9,
    first_name: "Kikelia",
    email: "kmatthesius8@rakuten.co.jp",
    gender: "Female",
    mobile_no: "188 989 9343",
  },
  {
    id: 10,
    first_name: "Adina",
    email: "acuolahan9@apache.org",
    gender: "Female",
    mobile_no: "251 762 1302",
  },
  {
    id: 11,
    first_name: "Bibby",
    email: "bleftleya@arizona.edu",
    gender: "Female",
    mobile_no: "500 569 5944",
  },
  {
    id: 12,
    first_name: "Aggy",
    email: "akilpatrickb@wordpress.org",
    gender: "Agender",
    mobile_no: "741 483 9199",
  },
  {
    id: 13,
    first_name: "Pacorro",
    email: "ppennyc@dmoz.org",
    gender: "Male",
    mobile_no: "831 664 9639",
  },
  {
    id: 14,
    first_name: "Chandler",
    email: "cboomesd@eventbrite.com",
    gender: "Male",
    mobile_no: "433 735 8401",
  },
  {
    id: 15,
    first_name: "Mathilde",
    email: "miacobuccie@mayoclinic.com",
    gender: "Female",
    mobile_no: "883 209 1432",
  },
  {
    id: 16,
    first_name: "Lilith",
    email: "lmalmarf@ucsd.edu",
    gender: "Female",
    mobile_no: "961 216 3441",
  },
  {
    id: 17,
    first_name: "Deirdre",
    email: "dgibbardg@shutterfly.com",
    gender: "Female",
    mobile_no: "665 414 7847",
  },
  {
    id: 18,
    first_name: "Remus",
    email: "rmacknockerh@github.io",
    gender: "Male",
    mobile_no: "669 629 1964",
  },
  {
    id: 19,
    first_name: "Bartholomew",
    email: "bwensleyi@mozilla.com",
    gender: "Male",
    mobile_no: "987 344 8103",
  },
  {
    id: 20,
    first_name: "Koral",
    email: "kwasonj@biglobe.ne.jp",
    gender: "Female",
    mobile_no: "767 492 9146",
  },
  {
    id: 21,
    first_name: "Elwood",
    email: "eclethrok@reddit.com",
    gender: "Male",
    mobile_no: "186 522 8617",
  },
  {
    id: 22,
    first_name: "Cyrillus",
    email: "creesl@taobao.com",
    gender: "Male",
    mobile_no: "745 837 5905",
  },
  {
    id: 23,
    first_name: "Hamil",
    email: "hnevem@people.com.cn",
    gender: "Male",
    mobile_no: "404 567 2701",
  },
  {
    id: 24,
    first_name: "Polly",
    email: "proysonn@illinois.edu",
    gender: "Female",
    mobile_no: "608 826 2521",
  },
  {
    id: 25,
    first_name: "Osbourne",
    email: "owhitecrosso@trellian.com",
    gender: "Male",
    mobile_no: "505 509 2458",
  },
  {
    id: 26,
    first_name: "Ed",
    email: "efedderp@huffingtonpost.com",
    gender: "Male",
    mobile_no: "291 513 7663",
  },
  {
    id: 27,
    first_name: "Emanuele",
    email: "epantherq@wikipedia.org",
    gender: "Male",
    mobile_no: "631 566 7973",
  },
  {
    id: 28,
    first_name: "Crista",
    email: "cmcgraffinr@xinhuanet.com",
    gender: "Female",
    mobile_no: "239 569 4685",
  },
  {
    id: 29,
    first_name: "Fons",
    email: "ftruckells@ebay.com",
    gender: "Male",
    mobile_no: "935 650 5927",
  },
  {
    id: 30,
    first_name: "Dorella",
    email: "dfaichneyt@yale.edu",
    gender: "Female",
    mobile_no: "931 119 2665",
  },
  {
    id: 31,
    first_name: "Celeste",
    email: "cdelaceyu@github.io",
    gender: "Female",
    mobile_no: "726 896 1250",
  },
  {
    id: 32,
    first_name: "Felicia",
    email: "fbookerv@phoca.cz",
    gender: "Genderqueer",
    mobile_no: "914 486 4011",
  },
  {
    id: 33,
    first_name: "Guillermo",
    email: "gokeshottw@kickstarter.com",
    gender: "Male",
    mobile_no: "949 262 5096",
  },
  {
    id: 34,
    first_name: "Patin",
    email: "pliffex@smh.com.au",
    gender: "Male",
    mobile_no: "933 281 8043",
  },
  {
    id: 35,
    first_name: "Gussie",
    email: "gablitty@hhs.gov",
    gender: "Female",
    mobile_no: "904 628 9088",
  },
  {
    id: 36,
    first_name: "Locke",
    email: "ladcockz@squarespace.com",
    gender: "Genderqueer",
    mobile_no: "865 254 9652",
  },
  {
    id: 37,
    first_name: "Isidora",
    email: "irenhard10@digg.com",
    gender: "Female",
    mobile_no: "602 528 5352",
  },
  {
    id: 38,
    first_name: "Javier",
    email: "jberecloth11@networkadvertising.org",
    gender: "Male",
    mobile_no: "267 283 3510",
  },
  {
    id: 39,
    first_name: "Kynthia",
    email: "kwasiela12@t.co",
    gender: "Female",
    mobile_no: "991 949 9375",
  },
  {
    id: 40,
    first_name: "Graehme",
    email: "gebden13@gov.uk",
    gender: "Male",
    mobile_no: "966 726 6531",
  },
  {
    id: 41,
    first_name: "Maurizia",
    email: "mlancetter14@wix.com",
    gender: "Female",
    mobile_no: "756 116 2240",
  },
  {
    id: 42,
    first_name: "Marcello",
    email: "mphilps15@sciencedirect.com",
    gender: "Male",
    mobile_no: "778 503 6852",
  },
  {
    id: 43,
    first_name: "Manda",
    email: "mhindrich16@desdev.cn",
    gender: "Female",
    mobile_no: "982 759 3497",
  },
  {
    id: 44,
    first_name: "Amandie",
    email: "abravington17@xrea.com",
    gender: "Female",
    mobile_no: "165 846 2542",
  },
  {
    id: 45,
    first_name: "Dierdre",
    email: "dbrazil18@nasa.gov",
    gender: "Female",
    mobile_no: "694 988 6055",
  },
  {
    id: 46,
    first_name: "Aguie",
    email: "acregin19@imageshack.us",
    gender: "Male",
    mobile_no: "723 323 3828",
  },
  {
    id: 47,
    first_name: "Nealson",
    email: "nfurnell1a@yandex.ru",
    gender: "Male",
    mobile_no: "558 353 7857",
  },
  {
    id: 48,
    first_name: "Clarette",
    email: "cboundey1b@e-recht24.de",
    gender: "Female",
    mobile_no: "892 736 9174",
  },
  {
    id: 49,
    first_name: "Maxy",
    email: "mrosenwasser1c@tuttocitta.it",
    gender: "Male",
    mobile_no: "268 808 1484",
  },
  {
    id: 50,
    first_name: "Camel",
    email: "cnieass1d@about.com",
    gender: "Female",
    mobile_no: "863 213 9123",
  },
];

export const getUsers = function (page, limit) {
  // 0 - 4 (for page 1)
  // 5 - 9 (for page 2) ....

  let data=[];
  for (let i = (page - 1) * limit; i < (page * limit) && users[i]; i++) {
    data.push(users[i])
  }
  return data;
};

export const getLength = function () {
    return users.length;
}
